name: gittuf Verification
on:
  push:
    branches:
      - main
jobs:
  gittuf-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@26235450ee63a0bb9d834ecd62b910783af72006
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd ci-demo
          gittuf verify-ref main
