name: gittuf Verification
on:
  push:
    branches:
      - main
jobs:
  gittuf-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Install gittuf
        uses: gittuf/gittuf-installer@f31e69c7c18c7473cbce18ed69a559b945d3a738
      - name: Checkout and verify repository
        run: |
          gittuf clone https://github.com/${{ github.repository }}
          cd ci-demo
          gittuf verify-ref main
